# Generated by Django 3.1.5 on 2021-01-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_Name',
            field=models.CharField(default='My Awesome Cart', max_length=30),
        ),
    ]
