# Generated by Django 3.1.5 on 2021-01-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='oder_id',
            new_name='order_id',
        ),
    ]
